name: Deploy via Git Pull on VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Setup SSH Agent
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH and Pull Latest Code
      run: |
        ssh -tt -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no \
        ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
          cd /var/www/html
          sudo git pull origin main
          sudo systemctl restart apache2
        EOF

