name: Deploy Static HTML to Remote VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup SSH Agent
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to remote server (to temp folder)
      run: |
        rsync -avz --delete \
          -e "ssh -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no" \
          ./ \
          ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/tmp/deploy-temp/

    - name: Move files to /var/www/html with sudo
      run: |
        ssh -tt -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no \
        ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} \
        "sudo rsync -av --delete /tmp/deploy-temp/ /var/www/html/ && sudo rm -rf /tmp/deploy-temp"

    - name: Restart Apache2
      run: |
        ssh -tt -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no \
        ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} \
        "sudo -n systemctl restart apache2"

